#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd simulation

rm -rf 0 constant/polyMesh logs foamLog.db p.foam
cleanCase

cd ..

# -----------------------------------------------------------------%
