#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

MESH=mesh

cd simulation

echo 'Create symbolic links to polyMesh in' $MESH
cd constant
mkdir polyMesh
cd polyMesh
ln -s ../../../$MESH/constant/polyMesh/boundary  .
ln -s ../../../$MESH/constant/polyMesh/faces     .
ln -s ../../../$MESH/constant/polyMesh/neighbour .
ln -s ../../../$MESH/constant/polyMesh/owner     .
ln -s ../../../$MESH/constant/polyMesh/points    .
cd ../..

rm -rf 0
cp -r 0.org 0

# Parallel ............................
runApplication decomposePar
# runParallel `getApplication`
mpirun -n `getNumberOfProcessors` `getApplication` -parallel 2>&1 | tee log.hisa

runParallel -s postProcess hisa -postProcess -func MachNo

cd ..

# -----------------------------------------------------------------%
